services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - '27017:27017'
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ships_data:/data/db
      - ./jsons:/tmp/jsons

volumes:
  ships_data:

